# Copyright (c) 2024 Tenstorrent AI ULC
# SPDX-License-Identifier: Apache-2.0

if(CONFIG_SOC_TT_BLACKHOLE_DMC)
  board_runner_args(openocd "--config=${BOARD_DIR}/support/tt_blackhole_dmc.cfg")
endif()

if(CONFIG_SOC_TT_BLACKHOLE_SMC)
  board_runner_args(openocd "--config=${BOARD_DIR}/support/tt_blackhole_smc.cfg" "--use-elf")
endif()

if(CONFIG_ARM)
  board_runner_args(stm32cubeprogrammer "--port=swd" "--reset-mode=hw")
endif()

if(CONFIG_TT_SRST_ASSIST)
  set(DMC_VARS "# Autogenerated file with variables to reset SMC. Don't edit!\n")
  string(APPEND DMC_VARS "set OPENOCD ${OPENOCD}\n")
  string(APPEND DMC_VARS "set OPENOCD_DEFAULT_PATH ${OPENOCD_DEFAULT_PATH}\n")
  string(APPEND DMC_VARS "set DMC_CFG ${CMAKE_CURRENT_LIST_DIR}/support/tt_blackhole_dmc.cfg\n")
  string(APPEND DMC_VARS "set RST_GPIO_REG ${CONFIG_TT_SRST_ASSIST_ADDR}\n")
  string(APPEND DMC_VARS "set RST_GPIO_SET_MASK ${CONFIG_TT_SRST_ASSIST_SET}\n")
  string(APPEND DMC_VARS "set RST_GPIO_CLR_MASK ${CONFIG_TT_SRST_ASSIST_CLR}\n")
  file(WRITE ${CMAKE_CURRENT_LIST_DIR}/support/smc-reset-vars.cfg ${DMC_VARS})
endif()

# Include debugger templates below (order is important)
include(${ZEPHYR_BASE}/boards/common/openocd.board.cmake)

if(CONFIG_ARM OR CONFIG_RISCV)
  include(${ZEPHYR_BASE}/boards/common/jlink.board.cmake)
endif()

if(CONFIG_ARM)
  include(${ZEPHYR_BASE}/boards/common/stm32cubeprogrammer.board.cmake)
endif()

board_set_flasher_ifnset(tt_flash)
board_finalize_runner_args(tt_flash)
