# Copyright (c) 2024 Tenstorrent AI ULC
# SPDX-License-Identifier: Apache-2.0

if(CONFIG_SOC_TT_BLACKHOLE_BMC)
  board_runner_args(openocd "--config=${BOARD_DIR}/support/tt_blackhole_bmc.cfg")
  board_runner_args(jlink "--device=STM32G0b1ce")
endif()

if(CONFIG_SOC_TT_BLACKHOLE_SMC)
  board_runner_args(openocd "--config=${BOARD_DIR}/support/tt_blackhole_smc.cfg" "--use-elf")
endif()

if(CONFIG_ARM)
  board_runner_args(stm32cubeprogrammer "--port=swd" "--reset-mode=hw")
endif()

if(CONFIG_SOC_TT_BLACKHOLE_SMC)
  set(BMC_VARS "# Autogenerated file with variables to reset BH core. Don't edit!\n")
  string(APPEND BMC_VARS "set OPENOCD ${OPENOCD}\n")
  string(APPEND BMC_VARS "set OPENOCD_DEFAULT_PATH ${OPENOCD_DEFAULT_PATH}\n")
  string(APPEND BMC_VARS "set BMC_CFG ${CMAKE_CURRENT_LIST_DIR}/support/tt_blackhole_bmc.cfg\n")
  if(CONFIG_BOARD_REVISION MATCHES "p300.*")
    # P300 has two reset GPIOs, on GPIOB pin 0 and 1
    string(APPEND BMC_VARS "set RST_GPIO_REG 0x50000418\n")
    string(APPEND BMC_VARS "set RST_GPIO_SET_MASK 0x30000\n")
    string(APPEND BMC_VARS "set RST_GPIO_CLR_MASK 0x3\n")
  else()
    # All other Blackhole cards have RST pin on GPIOB, pin 0
    string(APPEND BMC_VARS "set RST_GPIO_REG 0x50000418\n")
    string(APPEND BMC_VARS "set RST_GPIO_SET_MASK 0x10000\n")
    string(APPEND BMC_VARS "set RST_GPIO_CLR_MASK 0x1\n")
  endif()
  file(WRITE ${CMAKE_CURRENT_LIST_DIR}/support/bmc-reset-vars.cfg ${BMC_VARS})
endif()

# Include debugger templates below (order is important)
include(${ZEPHYR_BASE}/boards/common/openocd.board.cmake)

if(CONFIG_ARM OR CONFIG_RISCV)
  include(${ZEPHYR_BASE}/boards/common/jlink.board.cmake)
endif()

if(CONFIG_ARM)
  include(${ZEPHYR_BASE}/boards/common/stm32cubeprogrammer.board.cmake)
endif()

board_set_flasher_ifnset(tt_flash)
board_finalize_runner_args(tt_flash)
